waypoints:
  point_1:
    x: 7.567
    y: -7.588
    yaw: 1.547

  point_2:
    x: -0.059
    y: -8.732
    yaw: 1.571

  point_3:
    x: -6.859
    y: -7.333
    yaw: 2.169
  
  point_4:
    x: 2.864
    y: 16.499
    yaw: -2.105
  
  point_5:
    x: -6.986
    y: 16.181
    yaw: -2.097

